// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCYUS6bk7vS2far68Es9yagIm767LmyN-Y',
    appId: '1:515814555723:android:82979f99060a1e8140cdce',
    messagingSenderId: '515814555723',
    projectId: 'new-postman-f7033',
    databaseURL: 'https://new-postman-f7033.firebaseio.com',
    storageBucket: 'new-postman-f7033.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBavQU7yWEH4X_ryUxCCrutPFNAwdFOPEQ',
    appId: '1:515814555723:ios:885459416b60542940cdce',
    messagingSenderId: '515814555723',
    projectId: 'new-postman-f7033',
    databaseURL: 'https://new-postman-f7033.firebaseio.com',
    storageBucket: 'new-postman-f7033.appspot.com',
    iosClientId: '515814555723-aps1gmfbm0tni2529ihrofpd4hlfctl5.apps.googleusercontent.com',
    iosBundleId: 'com.it.postman',
  );
}
